# Opt-in context defaults for output sockets. Keep the pinned engine tree untouched.
function(tc_canvas_prepare_compiler source output)
    find_package(Git REQUIRED)
    set(patch "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/EnginePatches/MaterialGraphCompiler.cpp.patch")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}" "${patch}")
    file(READ "${source}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(SHA256 actual "${content}")
    if(NOT actual STREQUAL "5a28da500cf57a68c9ec308e64940aa490d5d93cc02dfb68456492ca9aaa9d76")
        message(FATAL_ERROR "Terrain Canvas: pinned MaterialGraphCompiler input changed: ${source} (${actual}). Review the engine upgrade before updating hashes; see docs/TerrainCanvasCompilerCompatibility.md.")
    endif()
    get_filename_component(directory "${output}" DIRECTORY)
    set(staging "${directory}/staging")
    file(MAKE_DIRECTORY "${staging}")
    file(WRITE "${staging}/MaterialGraphCompiler.cpp" "${content}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=GIT_DIR --unset=GIT_WORK_TREE
        "GIT_CEILING_DIRECTORIES=${directory}"
        "${GIT_EXECUTABLE}" -c core.autocrlf=true apply --whitespace=nowarn "${patch}"
        WORKING_DIRECTORY "${staging}" RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Terrain Canvas: cannot apply compiler patch: ${error}")
    endif()
    file(READ "${staging}/MaterialGraphCompiler.cpp" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(SHA256 actual "${content}")
    if(NOT actual STREQUAL "b8241e4918264033a3bb1ce147c9d26253c123549ed2bfaf57dcb7948df436a7")
        message(FATAL_ERROR "Terrain Canvas: compiler override output changed (${actual}). Review the patch and rerun the compiler compatibility tests before updating hashes.")
    endif()
    configure_file("${staging}/MaterialGraphCompiler.cpp" "${output}" COPYONLY)
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    tc_canvas_prepare_compiler("${TC_CANVAS_COMPILER_SOURCE}" "${TC_CANVAS_COMPILER_OUTPUT}")
endif()
