set(FILES
    Code/Include/TerrainCompositor/TerrainMaterialBindings.h
    Code/Include/TerrainCompositor/TerrainPreparationDependency.h
    Code/Include/TerrainCompositor/Internal/PendingCompositionInvalidation.h
    Code/Source/CompositionInvalidation.h
    Code/Include/TerrainCompositor/Internal/PreparedComposition.h
    Code/Source/CompositionPreparation.h
    Code/Source/CompositionPreparation.cpp
    Code/Include/TerrainCompositor/Internal/AssetSubscription.h
    Code/Include/TerrainCompositor/Internal/CacheLifecycle.h
    Code/Include/TerrainCompositor/Internal/RegistrationClient.h
    Code/Include/TerrainCompositor/Internal/MeshPlacementLifecycle.h
    Code/Include/TerrainCompositor/Internal/ProviderLifecycle.h
    Code/Include/TerrainCompositor/Components/HeightmapStampComponent.h
    Code/Include/TerrainCompositor/Components/HeightmapStampConfig.h
    Code/Include/TerrainCompositor/Components/ProceduralGroundGradientComponent.h
    Code/Include/TerrainCompositor/Components/TerrainCompositionGradientComponent.h
    Code/Include/TerrainCompositor/Components/TerrainCompositionHeightProviderComponent.h
    Code/Include/TerrainCompositor/Components/TerrainCompositionSurfaceProviderComponent.h
    Code/Include/TerrainCompositor/Components/TerrainMeshCutoutComponent.h
    Code/Include/TerrainCompositor/Components/TerrainMeshCutoutConfig.h
    Code/Include/TerrainCompositor/Components/TerrainMeshHeightStampComponent.h
    Code/Include/TerrainCompositor/Components/TerrainMeshHeightStampConfig.h
    Code/Include/TerrainCompositor/HeightmapControlThread.h
    Code/Include/TerrainCompositor/HeightmapData.h
    Code/Include/TerrainCompositor/HeightmapDataCache.h
    Code/Include/TerrainCompositor/HeightmapStampIdentity.h
    Code/Include/TerrainCompositor/HeightmapStampRegistration.h
    Code/Include/TerrainCompositor/HeightmapStampSampling.h
    Code/Include/TerrainCompositor/StampPlacement.h
    Code/Include/TerrainCompositor/SurfaceCompositionConfig.h
    Code/Include/TerrainCompositor/SurfaceStampSampling.h
    Code/Include/TerrainCompositor/TerrainCompositionBus.h
    Code/Include/TerrainCompositor/TerrainCompositionProviderBinding.h
    Code/Include/TerrainCompositor/TerrainCompositorTypeIds.h
    Code/Include/TerrainCompositor/TerrainExistenceBus.h
    Code/Include/TerrainCompositor/TerrainExistenceConfig.h
    Code/Include/TerrainCompositor/TerrainExistenceSampling.h
    Code/Include/TerrainCompositor/TerrainInvalidation.h
    Code/Include/TerrainCompositor/TerrainMeshCutoutData.h
    Code/Include/TerrainCompositor/TerrainMeshCutoutDataCache.h
    Code/Include/TerrainCompositor/TerrainMeshCutoutFeatureProcessor.h
    Code/Include/TerrainCompositor/TerrainMeshCutoutRegistration.h
    Code/Include/TerrainCompositor/TerrainMeshCutoutRenderRegistry.h
    Code/Include/TerrainCompositor/TerrainRenderQuery.h
    Code/Include/TerrainCompositor/TerrainSectorSampling.h
    Code/Include/TerrainCompositor/TerrainSectorRecovery.h
    Code/Include/TerrainCompositor/TerrainSectorSampleReuse.h
    Code/Include/TerrainCompositor/TerrainSectorDispatcher.h
    Code/Include/TerrainCompositor/Internal/RetainedCompositionMemory.h
    Code/Include/TerrainCompositor/TerrainSectorScheduling.h
    Code/Include/TerrainCompositor/TerrainSectorCoverage.h
    Code/Include/TerrainCompositor/TerrainProceduralSnapshot.h
    Code/Include/TerrainCompositor/ProceduralHillKernel.h
    Code/Include/TerrainCompositor/TerrainBatchCandidates.h
    Code/Include/TerrainCompositor/TerrainMeshCutoutSampling.h
    Code/Include/TerrainCompositor/TerrainMeshHeightData.h
    Code/Include/TerrainCompositor/TerrainMeshHeightDataCache.h
    Code/Include/TerrainCompositor/TerrainMeshHeightGapGpu.h
    Code/Include/TerrainCompositor/TerrainMeshHeightMapping.h
    Code/Include/TerrainCompositor/TerrainMeshHeightStampBus.h
    Code/Include/TerrainCompositor/TerrainMeshHeightStampRegistration.h
    Code/Include/TerrainCompositor/TerrainMeshHeightStampSampling.h
    Code/Include/TerrainCompositor/TerrainModelGeometry.h
    Code/Include/TerrainCompositor/TerrainQuality.h
    Code/Source/ProviderReflection.h
    Code/Source/ComponentConfiguration.h
    Code/Source/PublicationState.h
    Code/Include/TerrainCompositor/Internal/CompositionRegistrationState.h
    Code/Include/TerrainCompositor/Internal/CompositionRegistrations.h
    Code/Include/TerrainCompositor/Internal/TerrainTiming.h
    Code/Include/TerrainCompositor/Internal/AssetSnapshot.h
    Code/Source/AssetSource.h
    Code/Include/TerrainCompositor/Internal/AssetPreparation.h
    Code/Source/ModelAssetSource.h
    Code/Source/MeshPlacementLifecycle.cpp
    Code/Source/ImageSampling.h
    Code/Source/MeshCutoutTraversal.h
    Code/Source/StampMath.h
    Code/Source/Components/MeshPlacementHelpers.h
    Code/Source/Components/HeightmapStampComponent.cpp
    Code/Source/Components/HeightmapStampConfig.cpp
    Code/Source/Components/ProceduralGroundGradientComponent.cpp
    Code/Source/Components/TerrainCompositionGradientComponent.cpp
    Code/Source/Components/TerrainCompositionHeightProviderComponent.cpp
    Code/Source/Components/TerrainCompositionQueryHelpers.h
    Code/Source/Components/TerrainCompositionSurfaceProviderComponent.cpp
    Code/Source/Components/TerrainMeshCutoutComponent.cpp
    Code/Source/Components/TerrainMeshCutoutConfig.cpp
    Code/Source/Components/TerrainMeshHeightStampComponent.cpp
    Code/Source/Components/TerrainMeshHeightStampConfig.cpp
    Code/Source/HeightmapDataCache.cpp
    Code/Source/HeightmapStampIdentity.cpp
    Code/Source/HeightmapStampRegistration.cpp
    Code/Source/HeightmapStampSampling.cpp
    Code/Source/StampPlacement.cpp
    Code/Source/SurfaceCompositionConfig.cpp
    Code/Source/SurfaceStampSampling.cpp
    Code/Source/TerrainCompositionProviderBinding.cpp
    Code/Source/TerrainCompositorSystemComponent.cpp
    Code/Source/TerrainCompositorSystemComponent.h
    Code/Source/TerrainExistenceConfig.cpp
    Code/Source/TerrainExistenceSampling.cpp
    Code/Source/TerrainInvalidation.cpp
    Code/Source/TerrainMeshCutoutData.cpp
    Code/Source/TerrainMeshCutoutDataCache.cpp
    Code/Source/TerrainMeshCutoutFeatureProcessor.cpp
    Code/Source/TerrainMeshCutoutRegistration.cpp
    Code/Source/TerrainMeshCutoutRenderRegistry.cpp
    Code/Source/TerrainMeshCutoutSampling.cpp
    Code/Source/TerrainMeshHeightData.cpp
    Code/Source/TerrainMeshHeightDataCache.cpp
    Code/Source/TerrainMeshHeightGapGpu.cpp
    Code/Source/TerrainMeshHeightStampRegistration.cpp
    Code/Source/TerrainMeshHeightStampSampling.cpp
    Code/Source/TerrainModelGeometry.cpp
    Code/Source/TerrainQuality.cpp
)
