include_guard(GLOBAL)

set(TERRAIN_COMPOSITOR_POLYTREE_SOURCE_DIR "" CACHE PATH "Optional polytree source checkout")
set(TERRAIN_COMPOSITOR_ALGO_SOURCE_DIR "" CACHE PATH "Optional algo source checkout")
option(TERRAIN_COMPOSITOR_FETCH_DEPENDENCIES "Fetch pinned dependencies when packages are unavailable" ON)

# Targets are the authority, including those supplied by scene-polytree. Resolve
# algo first so polytree's transitive requirement cannot instantiate another copy.
function(terrain_compositor_require_dependencies)
    set(ALGO_BUILD_TESTS OFF)
    set(POLYTREE_BUILD_TESTS OFF)
    set(POLYTREE_BUILD_BENCHMARKS OFF)
    foreach(dependency IN ITEMS algo polytree)
        string(TOUPPER "${dependency}" upper)
        set(selected "")
        foreach(setting IN ITEMS TERRAIN_COMPOSITOR_${upper}_SOURCE_DIR SCENE_POLYTREE_${upper}_SOURCE_DIR)
            if(${setting})
                file(REAL_PATH "${${setting}}" candidate)
                if(selected AND NOT selected STREQUAL candidate)
                    message(FATAL_ERROR "Conflicting ${dependency} source overrides: ${selected} and ${candidate}; select one shared checkout")
                endif()
                set(selected "${candidate}")
            endif()
        endforeach()
        if(TARGET ${dependency}::${dependency})
            continue()
        endif()
        set(source "${TERRAIN_COMPOSITOR_${upper}_SOURCE_DIR}")
        # Honor the companion Gem's explicit selection even when we run first.
        if(NOT source)
            set(source "${SCENE_POLYTREE_${upper}_SOURCE_DIR}")
        endif()
        if(NOT source AND dependency STREQUAL "algo")
            set(source "${POLYTREE_ALGO_SOURCE_DIR}")
        endif()
        if(source)
            add_subdirectory("${source}" "${CMAKE_CURRENT_BINARY_DIR}/terrain-deps/${dependency}" EXCLUDE_FROM_ALL)
        else()
            if(dependency STREQUAL "algo")
                find_package(algo 0.0.1...<0.1 CONFIG QUIET GLOBAL)
                set(revision ea2e45f8c19ebe7deb44c85c91179e12fac57154)
            else()
                find_package(polytree 0.2...<0.3 CONFIG QUIET GLOBAL)
                set(revision 6a7e2ee401cb755a40512ab7b4630becf2eb9950)
            endif()
            if(NOT TARGET ${dependency}::${dependency})
                if(NOT TERRAIN_COMPOSITOR_FETCH_DEPENDENCIES)
                    message(FATAL_ERROR "TerrainCompositor requires ${dependency}::${dependency}; provide a package or TERRAIN_COMPOSITOR_${upper}_SOURCE_DIR")
                endif()
                include(FetchContent)
                FetchContent_Declare(${dependency}
                    GIT_REPOSITORY https://github.com/brooteskan/${dependency}.git
                    GIT_TAG ${revision})
                FetchContent_MakeAvailable(${dependency})
            endif()
        endif()
        if(NOT TARGET ${dependency}::${dependency})
            message(FATAL_ERROR "TerrainCompositor dependency did not export ${dependency}::${dependency}")
        endif()
    endforeach()
endfunction()
