set(FILES
    InternalHelperTests.cpp
    ImageRegistrationStateTests.cpp
    MeshRegistrationStateTests.cpp
    RegistrationStateReference.h
    TestMain.cpp
    TerrainTestFixtures.h
    ProceduralGroundGradientComponentTests.cpp
    ProceduralSnapshotTestSupport.h
    TerrainProceduralSnapshotTests.cpp
    HeightmapReconstructionTests.cpp
    TerrainMeshCutoutTests.cpp
    TerrainSectorLifetimeTests.cpp
    TerrainSectorSamplingTests.cpp
    SectorRayTracingMock.h
    TerrainMeshHeightStampTests.cpp
    TerrainMeshHeightGapGpuTests.cpp
    TerrainQualityTests.cpp
    TerrainRegistrationLifecycleTests.cpp
    TerrainModelCacheLifecycleTests.cpp
    TerrainMeshPlacementLifecycleTests.cpp
    TerrainProviderLifecycleTests.cpp
)
