set(FILES
    InternalHelperTests.cpp
    TestMain.cpp
    TerrainTestFixtures.h
    ProceduralGroundGradientComponentTests.cpp
    HeightmapReconstructionTests.cpp
    TerrainMeshCutoutTests.cpp
    TerrainMeshHeightStampTests.cpp
    TerrainMeshHeightGapGpuTests.cpp
    TerrainQualityTests.cpp
    TerrainRegistrationLifecycleTests.cpp
    TerrainModelCacheLifecycleTests.cpp
    TerrainMeshPlacementLifecycleTests.cpp
)
